FROM java:8-jre
MAINTAINER UTKARSH <mksinha006@gmail.com>
COPY ./target/Distributor-service-0.0.1-SNAPSHOT.jar /usr/app/src/Distributor-service-0.0.1-SNAPSHOT.jar

WORKDIR /usr/app/src

ENTRYPOINT ["java","-jar", "Disstributor-service-0.0.1-SNAPSHOT.jar"]