spring:
  data:
    mongodb:
      uri: mongodb://localhost/userProfileDb
      username: shweta
      password: Root@123
      database: userProfileDb
      port: 27017
      host: localhost
server:
  port: 8081